# Generated by Django 4.2.1 on 2023-05-25 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("countPeople", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ProfessionCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("countExpert", models.PositiveIntegerField()),
                ("countSemiExpert", models.PositiveIntegerField()),
                ("countNonExpert", models.PositiveIntegerField()),
                ("countTotal", models.PositiveIntegerField(null=True)),
                (
                    "dailyReport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="automation.dailyreport",
                    ),
                ),
                (
                    "profession",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="automation.profession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PositionCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.PositiveIntegerField()),
                (
                    "dailyReport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="automation.dailyreport",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="automation.position",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="positions",
            field=models.ManyToManyField(
                through="automation.PositionCount", to="automation.position"
            ),
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="professions",
            field=models.ManyToManyField(
                through="automation.ProfessionCount", to="automation.profession"
            ),
        ),
    ]
