# Generated by Django 4.2.1 on 2023-05-25 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0002_dailyreport_professioncount_positioncount_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="position", old_name="position", new_name="name",
        ),
    ]
