# Generated by Django 4.2.1 on 2023-05-25 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0003_rename_position_position_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profession", old_name="profession", new_name="name",
        ),
    ]
