# Generated by Django 4.2.1 on 2023-05-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0005_alter_professioncount_counttotal"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyreport",
            name="countPositions",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="countProfessions",
            field=models.IntegerField(default=0),
        ),
    ]
