# Generated by Django 4.2.1 on 2023-05-25 15:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0006_dailyreport_countpositions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyreport",
            name="contract_number",
            field=models.CharField(
                default="123456789",
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{1,10}$", "Enter a valid number."
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="employee",
            field=models.CharField(default="Default Employee", max_length=250),
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="employer",
            field=models.CharField(default="Default Employer", max_length=250),
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="project_name",
            field=models.CharField(default="Automation Project", max_length=250),
        ),
    ]
