# Generated by Django 4.2.1 on 2023-05-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "automation",
            "0007_dailyreport_contract_number_dailyreport_employee_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="name",
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name="profession",
            name="name",
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
