# Generated by Django 4.2.1 on 2023-05-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0009_machine_machinecount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="name",
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name="machine",
            name="type",
            field=models.IntegerField(
                choices=[(1, "سواری"), (2, "وانت"), (3, "تراک"), (4, "ابزار")]
            ),
        ),
    ]
