# Generated by Django 4.2.1 on 2023-05-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0010_alter_machine_name_alter_machine_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyreport",
            name="countMachines",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="machines",
            field=models.ManyToManyField(
                through="automation.MachineCount", to="automation.machine"
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="type",
            field=models.IntegerField(
                choices=[
                    (0, "نامشخص"),
                    (1, "سواری"),
                    (2, "وانت"),
                    (3, "تراک"),
                    (4, "ابزار"),
                ],
                default=0,
            ),
        ),
    ]
