# Generated by Django 4.2.1 on 2023-05-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0012_alter_machinecount_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyreport",
            name="weekday",
            field=models.IntegerField(
                choices=[
                    (1, "Monday"),
                    (2, "Tuesday"),
                    (3, "Wednesday"),
                    (4, "Thursday"),
                    (5, "Friday"),
                    (6, "Saturday"),
                    (7, "Sunday"),
                ],
                default=6,
            ),
        ),
    ]
