# Generated by Django 4.2.1 on 2023-06-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0017_material_unit_alter_dailyreport_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="machinecount", old_name="count", new_name="ActiveCount",
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="materials",
            field=models.ManyToManyField(
                through="automation.MaterialCount", to="automation.material"
            ),
        ),
        migrations.AddField(
            model_name="machinecount",
            name="InactiveCount",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="weekday",
            field=models.IntegerField(
                choices=[
                    (2, "دوشنبه"),
                    (3, "سه شنبه"),
                    (4, "چهارشنبه"),
                    (5, "پنج شنبه"),
                    (6, "جمعه"),
                    (0, "شنبه"),
                    (1, "یکشنبه"),
                ],
                default=5,
            ),
        ),
    ]
