# Generated by Django 4.2.1 on 2023-06-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0018_rename_count_machinecount_activecount_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="machinecount", name="ActiveCount",),
        migrations.RemoveField(model_name="machinecount", name="InactiveCount",),
        migrations.AddField(
            model_name="machinecount",
            name="activeCount",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="machinecount",
            name="inactiveCount",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
