# Generated by Django 4.2.1 on 2023-06-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0019_remove_machinecount_activecount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="machinecount",
            name="totalCount",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
