# Generated by Django 4.2.1 on 2023-06-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0020_machinecount_totalcount"),
    ]

    operations = [
        migrations.RemoveField(model_name="dailyreport", name="countMachines",),
        migrations.AddField(
            model_name="dailyreport",
            name="countActiveMachines",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="countAllMachines",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="countInactiveMachines",
            field=models.IntegerField(default=0),
        ),
    ]
