# Generated by Django 4.2.1 on 2023-06-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0021_remove_dailyreport_countmachines_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date",
            field=models.DateField(default="1402-03-12"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="weekday",
            field=models.IntegerField(
                choices=[
                    (2, "دوشنبه"),
                    (3, "سه شنبه"),
                    (4, "چهارشنبه"),
                    (5, "پنج شنبه"),
                    (6, "جمعه"),
                    (0, "شنبه"),
                    (1, "یکشنبه"),
                ],
                default=6,
            ),
        ),
    ]
