# Generated by Django 4.2.1 on 2023-06-02 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0022_equipe_alter_dailyreport_date_and_more"),
    ]

    operations = [
        migrations.RenameModel(old_name="Equipe", new_name="Contractor",),
    ]
