# Generated by Django 4.2.1 on 2023-06-02 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0024_equipe"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="equipe", unique_together={("profession", "contractor")},
        ),
    ]
