# Generated by Django 4.2.1 on 2023-06-02 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0025_alter_equipe_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="EqquipeCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("countExpert", models.PositiveIntegerField()),
                ("countSemiExpert", models.PositiveIntegerField()),
                ("countNonExpert", models.PositiveIntegerField()),
                ("countTotal", models.PositiveIntegerField(default=0)),
                (
                    "contractor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="automation.contractor",
                    ),
                ),
                (
                    "dailyReport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="automation.dailyreport",
                    ),
                ),
                (
                    "profession",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="automation.profession",
                    ),
                ),
            ],
            options={"unique_together": {("dailyReport", "profession", "contractor")},},
        ),
    ]
