# Generated by Django 4.2.1 on 2023-06-02 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0026_eqquipecount"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractorCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("countExpert", models.PositiveIntegerField()),
                ("countSemiExpert", models.PositiveIntegerField()),
                ("countNonExpert", models.PositiveIntegerField()),
                ("countTotal", models.PositiveIntegerField(default=0)),
                (
                    "contractor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="automation.contractor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EquipeCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("countExpert", models.PositiveIntegerField()),
                ("countSemiExpert", models.PositiveIntegerField()),
                ("countNonExpert", models.PositiveIntegerField()),
                ("countTotal", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="countContractors",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="countEquipes",
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(name="EqquipeCount",),
        migrations.AddField(
            model_name="equipecount",
            name="dailyReport",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="automation.dailyreport"
            ),
        ),
        migrations.AddField(
            model_name="equipecount",
            name="equipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="automation.equipe"
            ),
        ),
        migrations.AddField(
            model_name="contractorcount",
            name="dailyReport",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="automation.dailyreport"
            ),
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="contractors",
            field=models.ManyToManyField(
                through="automation.ContractorCount", to="automation.contractor"
            ),
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="equipes",
            field=models.ManyToManyField(
                through="automation.EquipeCount", to="automation.equipe"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="equipecount", unique_together={("dailyReport", "equipe")},
        ),
        migrations.AlterUniqueTogether(
            name="contractorcount", unique_together={("dailyReport", "contractor")},
        ),
    ]
