# Generated by Django 4.2.1 on 2023-06-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0027_contractorcount_equipecount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipe",
            name="name",
            field=models.CharField(default="", max_length=150),
        ),
    ]
