# Generated by Django 4.2.1 on 2023-06-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0028_equipe_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipe",
            name="name",
            field=models.CharField(default="", max_length=150, unique=True),
        ),
    ]
