# Generated by Django 4.2.1 on 2023-06-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0029_alter_equipe_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipe",
            name="name",
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
    ]
