# Generated by Django 4.2.1 on 2023-06-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0030_alter_equipe_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyreport",
            name="date",
            field=models.DateField(default="1402-03-13"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="weekday",
            field=models.IntegerField(
                choices=[
                    (2, "دوشنبه"),
                    (3, "سه شنبه"),
                    (4, "چهارشنبه"),
                    (5, "پنج شنبه"),
                    (6, "جمعه"),
                    (0, "شنبه"),
                    (1, "یکشنبه"),
                ],
                default=0,
            ),
        ),
    ]
