# Generated by Django 4.2.1 on 2023-06-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0031_alter_dailyreport_date_alter_dailyreport_weekday"),
    ]

    operations = [
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name="machine",
            name="type",
            field=models.IntegerField(
                choices=[(1, "سواری"), (2, "وانت"), (3, "تراک"), (4, "ابزار")],
                default=0,
            ),
        ),
    ]
