# Generated by Django 4.2.1 on 2023-06-05 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0033_task_alter_dailyreport_date_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="task", unique_together={("name", "equipe", "zone")},
        ),
        migrations.AlterUniqueTogether(
            name="taskreport", unique_together={("dailyReport", "task")},
        ),
    ]
