# Generated by Django 4.2.1 on 2023-06-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0035_task_unique_str"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="unique_str",
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
