# Generated by Django 4.2.1 on 2023-06-06 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0037_alter_dailyreport_date_alter_dailyreport_weekday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyreport",
            name="date",
            field=models.DateField(default="1402-03-17"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="weekday",
            field=models.IntegerField(
                choices=[
                    (2, "دوشنبه"),
                    (3, "سه شنبه"),
                    (4, "چهارشنبه"),
                    (5, "پنج شنبه"),
                    (6, "جمعه"),
                    (0, "شنبه"),
                    (1, "یکشنبه"),
                ],
                default=4,
            ),
        ),
    ]
