# Generated by Django 4.2.1 on 2023-06-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0039_taskreport_predonepercentage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="PreDoneVolume",
            field=models.FloatField(default=0.0),
        ),
    ]
