# Generated by Django 4.2.1 on 2023-06-07 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0041_rename_predonevolume_task_predonevolume"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskreport",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="automation.taskreport",
            ),
        ),
    ]
