# Generated by Django 4.2.1 on 2023-06-07 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0042_taskreport_parent"),
    ]

    operations = [
        migrations.RemoveField(model_name="task", name="preDoneVolume",),
        migrations.RemoveField(model_name="taskreport", name="preDonePercentage",),
    ]
