# Generated by Django 4.2.1 on 2023-06-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0043_remove_task_predonevolume_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskreport",
            name="preDonePercentage",
            field=models.FloatField(default=0.0),
        ),
    ]
