# Generated by Django 4.2.1 on 2023-06-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0044_taskreport_predonepercentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyreport",
            name="deletable",
            field=models.BooleanField(default=True),
        ),
    ]
