# Generated by Django 4.2.1 on 2023-06-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0048_alter_dailyreport_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyreport",
            name="date",
            field=models.DateTimeField(default="1402-03-17 18:30:03"),
        ),
    ]
