# Generated by Django 4.2.1 on 2023-06-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0049_alter_dailyreport_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyreport",
            name="date_created",
            field=models.DateTimeField(default="1402-03-18 12:09:02"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date",
            field=models.DateTimeField(default="1402-03-18 12:09:02"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="weekday",
            field=models.IntegerField(
                choices=[
                    (2, "دوشنبه"),
                    (3, "سه شنبه"),
                    (4, "چهارشنبه"),
                    (5, "پنج شنبه"),
                    (6, "جمعه"),
                    (0, "شنبه"),
                    (1, "یکشنبه"),
                ],
                default=5,
            ),
        ),
    ]
