# Generated by Django 4.2.1 on 2023-06-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0051_alter_dailyreport_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyreport",
            name="temperature_max",
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="temperature_min",
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date",
            field=models.DateTimeField(default="1402-03-18 12:18:52"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_created",
            field=models.DateTimeField(default="1402-03-18 12:18:52"),
        ),
    ]
