# Generated by Django 4.2.1 on 2023-06-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0053_dailyreport_weather_alter_dailyreport_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyreport",
            name="date",
            field=models.DateTimeField(default="1402-03-18 13:00:59"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_created",
            field=models.DateTimeField(default="1402-03-18 13:00:59"),
        ),
    ]
