# Generated by Django 4.2.1 on 2023-06-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0055_dailyreport_dust_value_alter_dailyreport_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyreport",
            name="consultor_name",
            field=models.CharField(default="Consultor Project", max_length=250),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date",
            field=models.DateTimeField(default="1402-03-18 13:05:24"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_created",
            field=models.DateTimeField(default="1402-03-18 13:05:24"),
        ),
    ]
