# Generated by Django 4.2.1 on 2023-06-16 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "automation",
            "0056_dailyreport_consultor_name_alter_dailyreport_date_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date",
            field=models.DateTimeField(default="1402-03-26 12:43:00"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_created",
            field=models.DateTimeField(default="1402-03-26 12:43:00"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="temperature_max",
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="temperature_min",
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="weekday",
            field=models.IntegerField(
                choices=[
                    (2, "دوشنبه"),
                    (3, "سه شنبه"),
                    (4, "چهارشنبه"),
                    (5, "پنج شنبه"),
                    (6, "جمعه"),
                    (0, "شنبه"),
                    (1, "یکشنبه"),
                ],
                default=6,
            ),
        ),
        migrations.AddField(
            model_name="materialcount",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="automation.provider",
            ),
        ),
    ]
