# Generated by Django 4.2.1 on 2023-06-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0057_provider_alter_dailyreport_date_and_more"),
    ]

    operations = [
        migrations.RenameModel(old_name="Provider", new_name="MaterialProvider",),
        migrations.AlterField(
            model_name="dailyreport",
            name="date",
            field=models.DateTimeField(default="1402-03-26 15:51:52"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_created",
            field=models.DateTimeField(default="1402-03-26 15:51:52"),
        ),
    ]
