# Generated by Django 4.2.1 on 2023-06-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0059_machineprovider_alter_dailyreport_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="machinecount",
            name="workHours",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date",
            field=models.DateTimeField(default="1402-03-27 23:41:11"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_created",
            field=models.DateTimeField(default="1402-03-27 23:41:11"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="weekday",
            field=models.IntegerField(
                choices=[
                    (2, "دوشنبه"),
                    (3, "سه شنبه"),
                    (4, "چهارشنبه"),
                    (5, "پنج شنبه"),
                    (6, "جمعه"),
                    (0, "شنبه"),
                    (1, "یکشنبه"),
                ],
                default=0,
            ),
        ),
    ]
