# Generated by Django 4.2.1 on 2023-06-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0063_task_completed_alter_dailyreport_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyreport",
            name="short_date",
            field=models.DateField(default="1402-04-04"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date",
            field=models.DateTimeField(default="1402-04-04 10:29:21"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_created",
            field=models.DateTimeField(default="1402-04-04 10:29:21"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="weekday",
            field=models.IntegerField(
                choices=[
                    (2, "دوشنبه"),
                    (3, "سه شنبه"),
                    (4, "چهارشنبه"),
                    (5, "پنج شنبه"),
                    (6, "جمعه"),
                    (0, "شنبه"),
                    (1, "یکشنبه"),
                ],
                default=1,
            ),
        ),
    ]
