# Generated by Django 4.2.1 on 2023-06-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0064_dailyreport_short_date_alter_dailyreport_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyreport",
            name="date_edited",
            field=models.DateTimeField(default="1402-04-04 19:36:41"),
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="editable",
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="edited",
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date",
            field=models.DateTimeField(default="1402-04-04 19:36:41"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_created",
            field=models.DateTimeField(default="1402-04-04 19:36:41"),
        ),
    ]
