# Generated by Django 4.2.1 on 2023-06-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0065_dailyreport_date_edited_dailyreport_editable_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyreport",
            name="date",
            field=models.DateTimeField(default="1402-04-04 19:37:20"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_created",
            field=models.DateTimeField(default="1402-04-04 19:37:20"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_edited",
            field=models.DateTimeField(default="1402-04-04 19:37:20"),
        ),
    ]
