# Generated by Django 4.2.1 on 2023-07-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0071_remove_suboperation_parentplussubs_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyreport",
            name="date",
            field=models.DateTimeField(default="1402-04-14 15:25:13"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_created",
            field=models.DateTimeField(default="1402-04-14 15:25:13"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_edited",
            field=models.DateTimeField(default="1402-04-14 15:25:13"),
        ),
        migrations.AlterField(
            model_name="operation",
            name="suboperations",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="operations",
                to="automation.suboperation",
            ),
        ),
    ]
