# Generated by Django 4.2.1 on 2023-07-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0078_alter_dailyreport_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="operationbreak", name="operation",),
        migrations.RemoveField(model_name="operationbreak", name="zone",),
        migrations.RemoveField(model_name="suboperation", name="parent",),
        migrations.RemoveField(model_name="suboperation", name="unit",),
        migrations.RemoveField(model_name="operation", name="suboperations",),
        migrations.AlterField(
            model_name="dailyreport",
            name="date",
            field=models.DateTimeField(default="1402-04-14 18:59:58"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_created",
            field=models.DateTimeField(default="1402-04-14 18:59:58"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_edited",
            field=models.DateTimeField(default="1402-04-14 18:59:58"),
        ),
        migrations.DeleteModel(name="Item",),
        migrations.DeleteModel(name="OperationBreak",),
        migrations.DeleteModel(name="SubOperation",),
    ]
