# Generated by Django 4.2.1 on 2023-07-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0080_alter_dailyreport_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyreport",
            name="date",
            field=models.DateTimeField(default="1402-04-14 19:07:19"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_created",
            field=models.DateTimeField(default="1402-04-14 19:07:19"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_edited",
            field=models.DateTimeField(default="1402-04-14 19:07:19"),
        ),
    ]
