# Generated by Django 4.2.1 on 2023-07-08 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0089_zoneoperation_unit_alter_dailyreport_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="zoneoperation",
            name="assignedAmount",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="zoneoperation",
            name="freeAmount",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date",
            field=models.DateTimeField(default="1402-04-17 10:03:58"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_created",
            field=models.DateTimeField(default="1402-04-17 10:03:58"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_edited",
            field=models.DateTimeField(default="1402-04-17 10:03:58"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="short_date",
            field=models.DateField(default="1402-04-17"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="weekday",
            field=models.IntegerField(
                choices=[
                    (2, "دوشنبه"),
                    (3, "سه شنبه"),
                    (4, "چهارشنبه"),
                    (5, "پنج شنبه"),
                    (6, "جمعه"),
                    (0, "شنبه"),
                    (1, "یکشنبه"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="automation.zoneoperation",
            ),
        ),
    ]
