# Generated by Django 4.2.1 on 2023-07-08 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0090_zoneoperation_assignedamount_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task", old_name="name", new_name="operation",
        ),
        migrations.AlterUniqueTogether(
            name="task", unique_together={("operation", "equipe", "zone")},
        ),
        migrations.AddField(
            model_name="task",
            name="suboperation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="automation.suboperation",
            ),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date",
            field=models.DateTimeField(default="1402-04-17 13:58:02"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_created",
            field=models.DateTimeField(default="1402-04-17 13:58:02"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_edited",
            field=models.DateTimeField(default="1402-04-17 13:58:02"),
        ),
    ]
