# Generated by Django 4.2.1 on 2023-07-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0091_rename_name_task_operation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyreport",
            name="date",
            field=models.DateTimeField(default="1402-04-17 14:17:52"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_created",
            field=models.DateTimeField(default="1402-04-17 14:17:52"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_edited",
            field=models.DateTimeField(default="1402-04-17 14:17:52"),
        ),
        migrations.AlterUniqueTogether(
            name="task",
            unique_together={("operation", "suboperation", "equipe", "zone")},
        ),
    ]
