# Generated by Django 4.2.1 on 2023-07-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0094_alter_dailyreport_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="zoneoperation",
            name="parentTasks",
            field=models.ManyToManyField(
                related_name="tasks", to="automation.parenttask"
            ),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date",
            field=models.DateTimeField(default="1402-04-18 12:32:01"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_created",
            field=models.DateTimeField(default="1402-04-18 12:32:01"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_edited",
            field=models.DateTimeField(default="1402-04-18 12:32:01"),
        ),
    ]
