# Generated by Django 4.2.1 on 2023-07-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "automation",
            "0095_zoneoperation_parenttasks_alter_dailyreport_date_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="parenttask",
            name="subtasks",
            field=models.ManyToManyField(related_name="subtasks", to="automation.task"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date",
            field=models.DateTimeField(default="1402-04-18 13:56:50"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_created",
            field=models.DateTimeField(default="1402-04-18 13:56:50"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_edited",
            field=models.DateTimeField(default="1402-04-18 13:56:50"),
        ),
    ]
