# Generated by Django 4.2.1 on 2023-07-11 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0098_taskreport_parenttask_alter_dailyreport_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="taskreport", name="parentTask",),
        migrations.AddField(
            model_name="taskreport",
            name="operation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="automation.operation",
            ),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date",
            field=models.DateTimeField(default="1402-04-20 12:13:17"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_created",
            field=models.DateTimeField(default="1402-04-20 12:13:17"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_edited",
            field=models.DateTimeField(default="1402-04-20 12:13:17"),
        ),
    ]
