# Generated by Django 4.2.1 on 2023-07-16 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0103_book_movie_alter_dailyreport_date_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="Book",),
        migrations.DeleteModel(name="Movie",),
        migrations.AddField(
            model_name="taskreport",
            name="parentTask",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="automation.parenttask",
            ),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date",
            field=models.DateTimeField(default="1402-04-25 22:23:19"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_created",
            field=models.DateTimeField(default="1402-04-25 22:23:19"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_edited",
            field=models.DateTimeField(default="1402-04-25 22:23:19"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="short_date",
            field=models.DateField(default="1402-04-25"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="weekday",
            field=models.IntegerField(
                choices=[
                    (2, "دوشنبه"),
                    (3, "سه شنبه"),
                    (4, "چهارشنبه"),
                    (5, "پنج شنبه"),
                    (6, "جمعه"),
                    (0, "شنبه"),
                    (1, "یکشنبه"),
                ],
                default=1,
            ),
        ),
    ]
