# Generated by Django 4.2.1 on 2023-07-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0105_alter_dailyreport_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskreport",
            name="reportDate",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date",
            field=models.DateTimeField(default="1402-04-25 22:41:51"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_created",
            field=models.DateTimeField(default="1402-04-25 22:41:51"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_edited",
            field=models.DateTimeField(default="1402-04-25 22:41:51"),
        ),
    ]
