# Generated by Django 4.2.1 on 2023-07-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0107_alter_dailyreport_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyreport",
            name="date",
            field=models.DateTimeField(default="1402-04-25 22:45:11"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_created",
            field=models.DateTimeField(default="1402-04-25 22:45:11"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_edited",
            field=models.DateTimeField(default="1402-04-25 22:45:11"),
        ),
        migrations.AlterField(
            model_name="taskreport", name="reportDate", field=models.DateTimeField(),
        ),
    ]
