# Generated by Django 4.2.1 on 2023-07-22 08:21

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0109_taskreport_equipe_taskreport_zone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyreport",
            name="created_at",
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date",
            field=django_jalali.db.models.jDateTimeField(default="1402-04-31 11:51:20"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_created",
            field=django_jalali.db.models.jDateTimeField(default="1402-04-31 11:51:20"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_edited",
            field=django_jalali.db.models.jDateTimeField(default="1402-04-31 11:51:20"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="short_date",
            field=django_jalali.db.models.jDateField(default="1402-04-31"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="weekday",
            field=models.IntegerField(
                choices=[
                    (2, "دوشنبه"),
                    (3, "سه شنبه"),
                    (4, "چهارشنبه"),
                    (5, "پنج شنبه"),
                    (6, "جمعه"),
                    (0, "شنبه"),
                    (1, "یکشنبه"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="parenttask",
            name="completion_date",
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="parenttask",
            name="start_date",
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="completion_date",
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="start_date",
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="taskreport",
            name="created_at",
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="taskreport",
            name="reportDate",
            field=django_jalali.db.models.jDateTimeField(),
        ),
    ]
