# Generated by Django 4.2.1 on 2023-08-01 10:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0112_alter_dailyreport_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, unique=True)),
                ("employer", models.CharField(max_length=250)),
                ("employee", models.CharField(max_length=250)),
                ("advisor", models.CharField(max_length=250)),
                ("contract_subject", models.CharField(max_length=250)),
                (
                    "contract_type",
                    models.IntegerField(
                        choices=[(1, "فهرستی"), (2, "لام سام"), (3, "فهرست خاص")]
                    ),
                ),
                (
                    "contract_number",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{1,10}$", "Enter a valid number."
                            )
                        ],
                    ),
                ),
                (
                    "start_date",
                    django_jalali.db.models.jDateField(blank=True, null=True),
                ),
                ("contract_duration", models.IntegerField()),
                ("contract_address", models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date",
            field=django_jalali.db.models.jDateTimeField(default="1402-05-10 14:04:00"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_created",
            field=django_jalali.db.models.jDateTimeField(default="1402-05-10 14:04:00"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_edited",
            field=django_jalali.db.models.jDateTimeField(default="1402-05-10 14:04:00"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="short_date",
            field=django_jalali.db.models.jDateField(default="1402-05-10"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="weekday",
            field=models.IntegerField(
                choices=[
                    (2, "دوشنبه"),
                    (3, "سه شنبه"),
                    (4, "چهارشنبه"),
                    (5, "پنج شنبه"),
                    (6, "جمعه"),
                    (0, "شنبه"),
                    (1, "یکشنبه"),
                ],
                default=3,
            ),
        ),
        migrations.CreateModel(
            name="ProjectUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("username", models.CharField(max_length=50, unique=True)),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("phone_number", models.CharField(max_length=15)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "projects",
                    models.ManyToManyField(
                        related_name="projects", to="automation.project"
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.AddField(
            model_name="project",
            name="ProjectUser",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="automation.projectuser"
            ),
        ),
    ]
