# Generated by Django 4.2.1 on 2023-08-01 10:37

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0113_project_alter_dailyreport_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyreport",
            name="date",
            field=django_jalali.db.models.jDateTimeField(default="1402-05-10 14:07:57"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_created",
            field=django_jalali.db.models.jDateTimeField(default="1402-05-10 14:07:57"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_edited",
            field=django_jalali.db.models.jDateTimeField(default="1402-05-10 14:07:57"),
        ),
        migrations.AlterField(
            model_name="projectuser",
            name="projects",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="projects", to="automation.project"
            ),
        ),
    ]
