# Generated by Django 4.2.1 on 2023-08-01 13:48

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        (
            "automation",
            "0122_remove_project_projectuser_alter_dailyreport_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyreport",
            name="date",
            field=django_jalali.db.models.jDateTimeField(default="1402-05-10 17:18:49"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_created",
            field=django_jalali.db.models.jDateTimeField(default="1402-05-10 17:18:49"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_edited",
            field=django_jalali.db.models.jDateTimeField(default="1402-05-10 17:18:49"),
        ),
    ]
