# Generated by Django 4.2.1 on 2023-08-01 13:52

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0124_alter_dailyreport_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyreport",
            name="date",
            field=django_jalali.db.models.jDateTimeField(default="1402-05-10 17:22:52"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_created",
            field=django_jalali.db.models.jDateTimeField(default="1402-05-10 17:22:52"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_edited",
            field=django_jalali.db.models.jDateTimeField(default="1402-05-10 17:22:52"),
        ),
        migrations.RemoveField(model_name="myuser", name="projects",),
        migrations.AddField(
            model_name="myuser",
            name="projects",
            field=models.ManyToManyField(
                related_name="projects", to="automation.project"
            ),
        ),
    ]
