# Generated by Django 4.2.1 on 2023-08-02 07:23

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0127_position_project_alter_dailyreport_date_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="positioncount", unique_together=set(),),
        migrations.AddField(
            model_name="positioncount",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="automation.project",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date",
            field=django_jalali.db.models.jDateTimeField(default="1402-05-11 10:53:36"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_created",
            field=django_jalali.db.models.jDateTimeField(default="1402-05-11 10:53:36"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_edited",
            field=django_jalali.db.models.jDateTimeField(default="1402-05-11 10:53:36"),
        ),
        migrations.AlterUniqueTogether(
            name="positioncount",
            unique_together={("dailyReport", "position", "project")},
        ),
    ]
