# Generated by Django 4.2.1 on 2023-08-02 07:24

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0128_alter_positioncount_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="professioncount", unique_together=set(),),
        migrations.AddField(
            model_name="profession",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="automation.project",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="professioncount",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="automation.project",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date",
            field=django_jalali.db.models.jDateTimeField(default="1402-05-11 10:54:50"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_created",
            field=django_jalali.db.models.jDateTimeField(default="1402-05-11 10:54:50"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_edited",
            field=django_jalali.db.models.jDateTimeField(default="1402-05-11 10:54:50"),
        ),
        migrations.AlterField(
            model_name="profession",
            name="name",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterUniqueTogether(
            name="professioncount",
            unique_together={("dailyReport", "profession", "project")},
        ),
    ]
