# Generated by Django 4.2.1 on 2023-08-02 07:27

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0129_alter_professioncount_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="machinecount", unique_together=set(),),
        migrations.AddField(
            model_name="machine",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="automation.project",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="machinecount",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="automation.project",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="machineprovider",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="automation.project",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date",
            field=django_jalali.db.models.jDateTimeField(default="1402-05-11 10:57:06"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_created",
            field=django_jalali.db.models.jDateTimeField(default="1402-05-11 10:57:06"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_edited",
            field=django_jalali.db.models.jDateTimeField(default="1402-05-11 10:57:06"),
        ),
        migrations.AlterField(
            model_name="machine", name="name", field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="machineprovider",
            name="name",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterUniqueTogether(
            name="machinecount",
            unique_together={("dailyReport", "machine", "provider", "project")},
        ),
    ]
