# Generated by Django 4.2.1 on 2023-08-02 07:35

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        (
            "automation",
            "0130_alter_machinecount_unique_together_machine_project_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="contractorcount", unique_together=set(),),
        migrations.AlterUniqueTogether(name="equipe", unique_together=set(),),
        migrations.AlterUniqueTogether(name="equipecount", unique_together=set(),),
        migrations.AlterUniqueTogether(name="materialcount", unique_together=set(),),
        migrations.AlterUniqueTogether(name="parenttask", unique_together=set(),),
        migrations.AlterUniqueTogether(name="suboperation", unique_together=set(),),
        migrations.AlterUniqueTogether(name="task", unique_together=set(),),
        migrations.AlterUniqueTogether(name="taskreport", unique_together=set(),),
        migrations.AlterUniqueTogether(name="zoneoperation", unique_together=set(),),
        migrations.AddField(
            model_name="contractor",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="automation.project",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contractorcount",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="automation.project",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="automation.project",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="equipe",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="automation.project",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="equipecount",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="automation.project",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="material",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="automation.project",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="materialcount",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="automation.project",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="materialprovider",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="automation.project",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="operation",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="automation.project",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parenttask",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="automation.project",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="suboperation",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="automation.project",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="automation.project",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="taskreport",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="automation.project",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="unit",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="automation.project",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="zone",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="automation.project",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="zoneoperation",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="automation.project",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contractor",
            name="name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date",
            field=django_jalali.db.models.jDateTimeField(default="1402-05-11 11:05:32"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_created",
            field=django_jalali.db.models.jDateTimeField(default="1402-05-11 11:05:32"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_edited",
            field=django_jalali.db.models.jDateTimeField(default="1402-05-11 11:05:32"),
        ),
        migrations.AlterField(
            model_name="material", name="name", field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="materialprovider",
            name="name",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="operation", name="name", field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="unit", name="name", field=models.CharField(max_length=25),
        ),
        migrations.AlterUniqueTogether(
            name="contractorcount",
            unique_together={("dailyReport", "contractor", "project")},
        ),
        migrations.AlterUniqueTogether(
            name="equipe", unique_together={("profession", "contractor", "project")},
        ),
        migrations.AlterUniqueTogether(
            name="equipecount", unique_together={("dailyReport", "equipe", "project")},
        ),
        migrations.AlterUniqueTogether(
            name="materialcount",
            unique_together={("dailyReport", "material", "provider", "project")},
        ),
        migrations.AlterUniqueTogether(
            name="parenttask",
            unique_together={("operation", "equipe", "zone", "project")},
        ),
        migrations.AlterUniqueTogether(
            name="suboperation", unique_together={("name", "parent", "project")},
        ),
        migrations.AlterUniqueTogether(
            name="task",
            unique_together={
                ("operation", "suboperation", "equipe", "zone", "project")
            },
        ),
        migrations.AlterUniqueTogether(
            name="taskreport", unique_together={("dailyReport", "task", "project")},
        ),
        migrations.AlterUniqueTogether(
            name="zoneoperation", unique_together={("operation", "zone", "project")},
        ),
    ]
