# Generated by Django 4.2.1 on 2023-08-02 07:37

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0131_alter_contractorcount_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="dailyReports",
            field=models.ManyToManyField(
                related_name="dailyReports", to="automation.dailyreport"
            ),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date",
            field=django_jalali.db.models.jDateTimeField(default="1402-05-11 11:07:26"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_created",
            field=django_jalali.db.models.jDateTimeField(default="1402-05-11 11:07:26"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_edited",
            field=django_jalali.db.models.jDateTimeField(default="1402-05-11 11:07:26"),
        ),
    ]
