# Generated by Django 4.2.1 on 2023-08-02 17:43

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0132_project_dailyreports_alter_dailyreport_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyreport",
            name="date",
            field=django_jalali.db.models.jDateTimeField(default="1402-05-11 21:13:38"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_created",
            field=django_jalali.db.models.jDateTimeField(default="1402-05-11 21:13:38"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_edited",
            field=django_jalali.db.models.jDateTimeField(default="1402-05-11 21:13:38"),
        ),
        migrations.AlterUniqueTogether(
            name="contractor", unique_together={("project", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="dailyreport", unique_together={("project", "short_date")},
        ),
        migrations.AlterUniqueTogether(
            name="machine", unique_together={("name", "project")},
        ),
        migrations.AlterUniqueTogether(
            name="machineprovider", unique_together={("name", "project")},
        ),
        migrations.AlterUniqueTogether(
            name="material", unique_together={("project", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="materialprovider", unique_together={("project", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="operation", unique_together={("project", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="position", unique_together={("name", "project")},
        ),
        migrations.AlterUniqueTogether(
            name="profession", unique_together={("name", "project")},
        ),
        migrations.AlterUniqueTogether(
            name="unit", unique_together={("project", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="zone", unique_together={("name", "project")},
        ),
    ]
