# Generated by Django 4.2.1 on 2023-08-10 14:47

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0147_issuereport_completion_date_issuereport_solved_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyreport",
            name="date",
            field=django_jalali.db.models.jDateTimeField(default="1402-05-19 18:17:36"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_created",
            field=django_jalali.db.models.jDateTimeField(default="1402-05-19 18:17:36"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_edited",
            field=django_jalali.db.models.jDateTimeField(default="1402-05-19 18:17:36"),
        ),
        migrations.AlterUniqueTogether(
            name="issuereport",
            unique_together={
                ("project", "issue", "projectField", "zone", "description")
            },
        ),
    ]
