# Generated by Django 4.2.1 on 2023-08-10 18:47

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0149_issuereport_started_alter_dailyreport_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="issuereport",
            name="issueCounts",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="issueCounts",
                to="automation.issuecount",
            ),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date",
            field=django_jalali.db.models.jDateTimeField(default="1402-05-19 22:17:45"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_created",
            field=django_jalali.db.models.jDateTimeField(default="1402-05-19 22:17:45"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_edited",
            field=django_jalali.db.models.jDateTimeField(default="1402-05-19 22:17:45"),
        ),
    ]
