# Generated by Django 4.2.1 on 2023-08-16 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("automation", "0150_issuereport_issuecounts_alter_dailyreport_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractor",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="automation.project"
            ),
        ),
        migrations.AlterField(
            model_name="contractorcount",
            name="contractor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="automation.contractor"
            ),
        ),
        migrations.AlterField(
            model_name="contractorcount",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="automation.project"
            ),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date",
            field=django_jalali.db.models.jDateTimeField(default="1402-05-25 11:16:12"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_created",
            field=django_jalali.db.models.jDateTimeField(default="1402-05-25 11:16:12"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_edited",
            field=django_jalali.db.models.jDateTimeField(default="1402-05-25 11:16:12"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="automation.project"
            ),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="short_date",
            field=django_jalali.db.models.jDateField(default="1402-05-25"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="weekday",
            field=models.IntegerField(
                choices=[
                    (2, "دوشنبه"),
                    (3, "سه شنبه"),
                    (4, "چهارشنبه"),
                    (5, "پنج شنبه"),
                    (6, "جمعه"),
                    (0, "شنبه"),
                    (1, "یکشنبه"),
                ],
                default=4,
            ),
        ),
        migrations.AlterField(
            model_name="equipe",
            name="contractor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="automation.contractor"
            ),
        ),
        migrations.AlterField(
            model_name="equipe",
            name="profession",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="automation.profession"
            ),
        ),
        migrations.AlterField(
            model_name="equipe",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="automation.project"
            ),
        ),
        migrations.AlterField(
            model_name="equipecount",
            name="equipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="automation.equipe"
            ),
        ),
        migrations.AlterField(
            model_name="equipecount",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="automation.project"
            ),
        ),
        migrations.AlterField(
            model_name="hardware",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="automation.project"
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="automation.project"
            ),
        ),
        migrations.AlterField(
            model_name="issuecount",
            name="issue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="automation.issuereport"
            ),
        ),
        migrations.AlterField(
            model_name="issuecount",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="automation.project"
            ),
        ),
        migrations.AlterField(
            model_name="issuereport",
            name="issue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="automation.issue"
            ),
        ),
        migrations.AlterField(
            model_name="issuereport",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="automation.project"
            ),
        ),
        migrations.AlterField(
            model_name="issuereport",
            name="projectField",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="automation.projectfield",
            ),
        ),
        migrations.AlterField(
            model_name="issuereport",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="automation.zone"
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="hardware",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="automation.hardware",
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="automation.project"
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="automation.machinefamily",
            ),
        ),
        migrations.AlterField(
            model_name="machinecount",
            name="hardware",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="automation.hardware"
            ),
        ),
        migrations.AlterField(
            model_name="machinecount",
            name="machine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="automation.machine"
            ),
        ),
        migrations.AlterField(
            model_name="machinecount",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="automation.project"
            ),
        ),
        migrations.AlterField(
            model_name="machinecount",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="automation.machineprovider",
            ),
        ),
        migrations.AlterField(
            model_name="machinecount",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="automation.machinefamily",
            ),
        ),
        migrations.AlterField(
            model_name="machinefamily",
            name="hardware",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="automation.hardware",
            ),
        ),
        migrations.AlterField(
            model_name="machinefamily",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="automation.project"
            ),
        ),
        migrations.AlterField(
            model_name="machineprovider",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="automation.project"
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="automation.project"
            ),
        ),
        migrations.AlterField(
            model_name="materialcount",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="automation.material"
            ),
        ),
        migrations.AlterField(
            model_name="materialcount",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="automation.project"
            ),
        ),
        migrations.AlterField(
            model_name="materialcount",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="automation.materialprovider",
            ),
        ),
        migrations.AlterField(
            model_name="materialcount",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="automation.unit"
            ),
        ),
        migrations.AlterField(
            model_name="materialprovider",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="automation.project"
            ),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="automation.project"
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="operation_unit",
                to="automation.unit",
            ),
        ),
        migrations.AlterField(
            model_name="parenttask",
            name="equipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="automation.equipe"
            ),
        ),
        migrations.AlterField(
            model_name="parenttask",
            name="operation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="automation.zoneoperation",
            ),
        ),
        migrations.AlterField(
            model_name="parenttask",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="automation.project"
            ),
        ),
        migrations.AlterField(
            model_name="parenttask",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="automation.unit"
            ),
        ),
        migrations.AlterField(
            model_name="parenttask",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="automation.zone"
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="automation.project"
            ),
        ),
        migrations.AlterField(
            model_name="positioncount",
            name="position",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="automation.position"
            ),
        ),
        migrations.AlterField(
            model_name="positioncount",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="automation.project"
            ),
        ),
        migrations.AlterField(
            model_name="profession",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="automation.project"
            ),
        ),
        migrations.AlterField(
            model_name="professioncount",
            name="profession",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="automation.profession"
            ),
        ),
        migrations.AlterField(
            model_name="professioncount",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="automation.project"
            ),
        ),
        migrations.AlterField(
            model_name="projectfield",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="automation.project"
            ),
        ),
        migrations.AlterField(
            model_name="suboperation",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="automation.operation"
            ),
        ),
        migrations.AlterField(
            model_name="suboperation",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="automation.project"
            ),
        ),
        migrations.AlterField(
            model_name="suboperation",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="automation.unit"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="equipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="automation.equipe"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="operation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="automation.zoneoperation",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="automation.parenttask"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="automation.project"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="suboperation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="automation.suboperation",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="automation.unit"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="automation.zone"
            ),
        ),
        migrations.AlterField(
            model_name="taskreport",
            name="equipe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="automation.equipe",
            ),
        ),
        migrations.AlterField(
            model_name="taskreport",
            name="operation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="automation.operation",
            ),
        ),
        migrations.AlterField(
            model_name="taskreport",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="automation.taskreport",
            ),
        ),
        migrations.AlterField(
            model_name="taskreport",
            name="parentTask",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="automation.parenttask",
            ),
        ),
        migrations.AlterField(
            model_name="taskreport",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="automation.project"
            ),
        ),
        migrations.AlterField(
            model_name="taskreport",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="automation.task"
            ),
        ),
        migrations.AlterField(
            model_name="taskreport",
            name="zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="automation.zone",
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="automation.unit",
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="automation.project"
            ),
        ),
        migrations.AlterField(
            model_name="zone",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="automation.project"
            ),
        ),
        migrations.AlterField(
            model_name="zoneoperation",
            name="operation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="automation.operation"
            ),
        ),
        migrations.AlterField(
            model_name="zoneoperation",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="automation.project"
            ),
        ),
        migrations.AlterField(
            model_name="zoneoperation",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="automation.unit"
            ),
        ),
        migrations.AlterField(
            model_name="zoneoperation",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="automation.zone"
            ),
        ),
    ]
