# Generated by Django 4.2.1 on 2023-08-20 09:47

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0153_alter_dailyreport_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="temp_code",
            field=models.CharField(default="*", max_length=5),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date",
            field=django_jalali.db.models.jDateTimeField(default="1402-05-29 13:17:30"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_created",
            field=django_jalali.db.models.jDateTimeField(default="1402-05-29 13:17:30"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_edited",
            field=django_jalali.db.models.jDateTimeField(default="1402-05-29 13:17:30"),
        ),
        migrations.AlterField(
            model_name="project",
            name="contract_number",
            field=models.CharField(max_length=15),
        ),
    ]
