# Generated by Django 4.2.1 on 2023-08-20 11:04

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0155_alter_dailyreport_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyreport",
            name="date",
            field=django_jalali.db.models.jDateTimeField(default="1402-05-29 14:34:07"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_created",
            field=django_jalali.db.models.jDateTimeField(default="1402-05-29 14:34:07"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_edited",
            field=django_jalali.db.models.jDateTimeField(default="1402-05-29 14:34:07"),
        ),
        migrations.AlterField(
            model_name="parenttask",
            name="unique_str",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="task",
            name="unique_str",
            field=models.CharField(max_length=250),
        ),
    ]
