# Generated by Django 4.2.1 on 2023-08-21 08:35

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0157_project_final_worth_alter_dailyreport_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="issuecount",
            name="state",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date",
            field=django_jalali.db.models.jDateTimeField(default="1402-05-30 12:05:24"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_created",
            field=django_jalali.db.models.jDateTimeField(default="1402-05-30 12:05:24"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_edited",
            field=django_jalali.db.models.jDateTimeField(default="1402-05-30 12:05:24"),
        ),
    ]
