# Generated by Django 4.2.1 on 2023-08-27 06:33

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0160_alter_parenttask_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="parenttask",
            name="equipe",
            field=models.ForeignKey(
                default=29,
                on_delete=django.db.models.deletion.PROTECT,
                to="automation.contractor",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task",
            name="equipe",
            field=models.ForeignKey(
                default=29,
                on_delete=django.db.models.deletion.PROTECT,
                to="automation.contractor",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date",
            field=django_jalali.db.models.jDateTimeField(default="1402-06-05 10:02:24"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_created",
            field=django_jalali.db.models.jDateTimeField(default="1402-06-05 10:02:24"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_edited",
            field=django_jalali.db.models.jDateTimeField(default="1402-06-05 10:02:24"),
        ),
    ]
