# Generated by Django 4.2.1 on 2023-08-27 07:00

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        (
            "automation",
            "0161_parenttask_equipe_task_equipe_alter_dailyreport_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyreport",
            name="date",
            field=django_jalali.db.models.jDateTimeField(default="1402-06-05 10:30:50"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_created",
            field=django_jalali.db.models.jDateTimeField(default="1402-06-05 10:30:50"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date_edited",
            field=django_jalali.db.models.jDateTimeField(default="1402-06-05 10:30:50"),
        ),
        migrations.AlterUniqueTogether(
            name="parenttask",
            unique_together={("operation", "equipe", "zone", "project")},
        ),
        migrations.AlterUniqueTogether(
            name="task",
            unique_together={
                ("operation", "suboperation", "equipe", "zone", "project")
            },
        ),
    ]
